language: node_js
node_js:
  - stable
script:
  - ./scripts/setup.bash
  - ./scripts/lint.bash
  - ./scripts/test.bash
cache:
  directories:
    - node_modules
branches:
  only:
    - trunk
    - megan
